ingress:
  hosts:
  - paths:
    - /
    host: 'siji-test-stagecraft-2-micro-service-2-argocd.diagility.com'
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  enabled: 'true'
image:
  tag: latest
  repository: registry.ustpace.com/docker-sandbox/siji-test-stagecraft-2-micro-service-2
  pullPolicy: Always
serviceAccount:
  create: 'false'
